#!/bin/sh

/bin/mount -t proc none /proc
/bin/mount -t sysfs sysfs /sys

cat <<'EOF'
     _            _     _                  
    | | ___   ___| |   (_)_ __  _   ___  __
 _  | |/ _ \ / _ \ |   | | '_ \| | | \ \/ /
| |_| | (_) |  __/ |___| | | | | |_| |>  < 
 \___/ \___/ \___|_____|_|_| |_|\__,_/_/\_\

EOF
echo 'Enjoy your new system!'

if [ -x /linuxrc ]; then
  /linuxrc
fi
/bin/sh
