#!/bin/sh

gotonewroot() {
  ROOTDIR=/mnt/root
  ROOTDEV=/dev/sda
  
  echo -n "Mount new root ..."
    [ ! -d $ROOTDIR ] && mkdir -p $ROOTDIR
    mount $ROOTDEV $ROOTDIR || return
  check_status
  
  mount --move /sys $ROOTDIR/sys
  mount --move /proc $ROOTDIR/proc
  mount --move /dev $ROOTDIR/dev
  
  exec switch_root $ROOTDIR /sbin/init
}

. /etc/rc.d/init.d/functions

PATH=/bin:/sbin:/usr/bin:/usr/sbin

echo -n "Start in initramfs"

for i in proc sys; do
  [ ! -d /$i ] && mkdir -p /$i
done
mount -t proc none /proc
mount -t sysfs none /sys

[ ! -d /dev ] && mkdir -p /dev
mount -t tmpfs none /dev

echo -n "Start hotplug ..."
  echo "/sbin/mdev" > /proc/sys/kernel/hotplug
  mdev -s
check_status

echo -n "Start pseudo terminal ..."
  [ ! -d /dev/pts ] && mkdir -p /dev/pts
  mount -t devpts -o mode=0755 devpts /dev/pts
check_status

# echo -n "Redirect standard I/O ..."
#   IODEV=/dev/ttyAMA0
#   [ -c /dev/$IODEV ] && exec <$IODEV >$IODEV 2>$IODEV
# check_status

gotonewroot

echo "Pass through to terminal ..."
exec /bin/sh
