#!/bin/sh

. /etc/rc.d/init.d/functions

for i in proc sys dev; do
  [ ! -d /$i ] && mkdir -p /$i
done
mount -t proc none /proc
mount -t sysfs none /sys
mount -t tmpfs none /dev

echo "/sbin/mdev" > /proc/sys/kernel/hotplug
mdev -s

[ ! -d /dev/pts ] && mkdir -p /dev/pts
mount -t devpts -o mode=0755 devpts /dev/pts

[ ! -c /dev/null ] && mknod -m 0666 /dev/null c 1 3
[ ! -c /dev/console ] && mknod /dev/console c 5 1

# IODEV=/dev/console
# [ -c $IODEV ] && exec <$IODEV &>$IODEV
