#!/bin/sh

# System Startup Script
#

. /etc/rc.d/init.d/functions

PATH=/bin:/sbin:/usr/bin:/usr/sbin

# should be done in /init
# . /etc/rc.d/init.d/sysinit

# echo -n "Redirect standard I/O ..."
#   IODEV=/dev/console
#   [ -c /dev/$IODEV ] && exec <$IODEV >$IODEV 2>$IODEV
# check_status

echo -n "Setting hostname ..." 
  [ -f /etc/hostname ] && hostname -F /etc/hostname || hostname bbqLinux
check_status

echo -n "Setting up interface lo ..."
  ifconfig lo up 127.0.0.1
check_status

echo -n "Adding route entry for lo ..."
  route add -net 127.0.0.0 netmask 255.0.0.0 lo
check_status

echo -n "Loading modules ..."
  [ -f /etc/rc.d/init.d/module ] && /etc/rc.d/init.d/module start || true
check_status

echo "Running start scripts."
  for i in /etc/rc.d/start/*; do
    if [ -x $i ]; then
      $i start
    fi
  done

cat <<'BannerEOF'
 _     _           _     _                  
| |__ | |__   __ _| |   (_)_ __  _   ___  __
| '_ \| '_ \ / _` | |   | | '_ \| | | \ \/ /
| |_) | |_) | (_| | |___| | | | | |_| |>  < 
|_.__/|_.__/ \__, |_____|_|_| |_|\__,_/_/\_\
                |_|                         
BannerEOF
