#!/bin/sh

# System Startup Script
#

. /etc/rc.d/init.d/functions

PATH=/bin:/sbin:/usr/bin:/usr/sbin

/bin/mount -t proc none /proc
/bin/mount -t sysfs none /sys
/bin/mount -t tmpfs none /dev
[ -c /dev/null ] || mknod -m 0666 /dev/null c 1 3
[ -c /dev/ttyS1 ] || mknod -m 0666 /dev/ttyS1 c 4 65
[ -c /dev/console ] || mknod /dev/console c 5 1

echo -n "Start hotplug ..."
  echo "/sbin/mdev" > /proc/sys/kernel/hotplug
  /sbin/mdev -s
check_status

echo -n "Start pseudo terminal ..."
  mkdir /dev/pts
  /bin/mount -t devpts -o mode=0755 devpts /dev/pts
check_status

# echo -n "Redirect standard I/O ..."
#   IODEV=/dev/console
#   [ -c /dev/$IODEV ] && exec <$IODEV >$IODEV 2>$IODEV
# check_status

echo -n "Setting hostname ..." 
  [ -f /etc/hostname ] && hostname -F /etc/hostname || hostname bbqLinux
check_status

echo -n "Setting up interface lo ..."
  ifconfig lo up 127.0.0.1
check_status

echo -n "Adding route entry for lo ..."
  route add -net 127.0.0.0 netmask 255.0.0.0 lo
check_status

echo -n "Loading modules ..."
  [ -f /etc/rc.d/init.d/module ] && /etc/rc.d/init.d/module start || true
check_status

echo "Running start scripts."
  for i in /etc/rc.d/start/*; do
    if [ -x $i ]; then
      $i start
    fi
  done

cat <<'BannerEOF'
 _     _           _     _                  
| |__ | |__   __ _| |   (_)_ __  _   ___  __
| '_ \| '_ \ / _` | |   | | '_ \| | | \ \/ /
| |_) | |_) | (_| | |___| | | | | |_| |>  < 
|_.__/|_.__/ \__, |_____|_|_| |_|\__,_/_/\_\
                |_|                         
BannerEOF
